### ISSUE TITLE
Error when pulling from external resource (DO Spaces)

### ISSUE THREAD

**Issue by davidatkinswwt** [aryehraber/statamic-color-extractor#10]
Hey @aryehraber

Thank you for putting this package out and I do see it is not actively maintained/supported.

I initially used this package with "local" assets working with no problems at all. 

The project has since grown and using external storage seemed the best option to keep things clean. 

```
<div
      class="border-8"
      style="border-color: {{ featured_media | color:average }};"
  >
    <img class="h-full w-full" src="{{ glide:featured_media preset="sm" }}" />
</div>


// Tag pair

{{ featured_media }}
  <div class="border-8" style="border-color: {{ url | color:average }};">
    <img class="h-full w-full" src="{{ url }}" />
  </div>
 {{ /featured_media }}
```

Is there something I am missing when using External Resources or is it not supported at this time? 

Thanks!

**Comment by aryehraber** [comment]
Hi @davidatkinswwt! 

To be honest, I've never tried using this addon with an external filesystem/storage. I'm not really sure what the difference would be from an addon-development POV since the addon uses Statamic's own `Asset` class, but perhaps there are some additional considerations when dealing with non-local filesystems. 

Are you able to provide some more details? What exactly is going wrong and are there error messages & logs that you can share?

**Comment by davidatkinswwt** [comment]
When using the following I setup I receive the URL of the image asset along with the same image being rendered by the <img> tag. Where the style border-color usually returned a HEX value when using a local asset. 

**Input:**
```
<div
      class="border-8"
      style="border-color: {{ glide:featured_media | color:average }};"
  >
    <img class="h-full w-full" src="{{ glide:featured_media }}" />
</div>
```


**Output:**
```
<div>
    <div class="border-8" style="border-color: https://bucket.nyc3.digitaloceanspaces.com/containers/do_assets/media/events/featured_media.jpg;">
      <img class="h-full w-full" src="https://bucket.nyc3.digitaloceanspaces.com/containers/do_assets/media/events/featured_media.jpg">
    </div>
  </div>
```

If I use {{ featured_media | color:average }} without the glide tag I receive a stack error stating: "Image source not readable".

I am using Antlers Runtime but switching to regex still yields same results. 

Thanks

**Comment by aryehraber** [comment]
Ah ok, yeah there's definitely something going wrong there... It'll be tricky to debug this without an external storage setup.

My free time is very limited unfortunately, so the less setup I need to do, the quicker I'll (hopefully) be able to debug the issue. Would you be willing/able to temporarily share your project with access to the DO Space, or perhaps to create and share a new temp. project (incl. a DO Space) with a basic template setup to recreate the issue?

**Comment by davidatkinswwt** [comment]
Here you go!

I have added a DO space and uploaded the env file as well. 

The area in question is in home.antlers.html, everything else was for someone else 😅

https://github.com/davidatkinswwt/testsite

**Comment by aryehraber** [comment]
Fantastic, thank you! I'll try my best to have a look this weekend and keep you posted.

**Comment by aryehraber** [comment]
Hi @davidatkinswwt, this issue should be fixed in the latest release (`v1.3.0`). Please let me know how it goes on your end after updating!

**Comment by davidatkinswwt** [comment]
Works great. Thank you again for taking the time to update this! 🥳

**Comment by aryehraber** [comment]
You're welcome, enjoy! And thanks again for providing the test project 🙏
