### ISSUE TITLE
Statamic 5 Support

### ISSUE THREAD

**Issue by DanielDarrenJones** [aryehraber/statamic-color-extractor#14]
Hi, are there any plans to update this to Statamic 5 please?

**Comment by aryehraber** [comment]
Hey @DanielDarrenJones! Yeah, I'm happy to update to V5, just haven't had the time to test it. I can bump the Composer dependency for Statamic and maybe you can report back?

**Comment by DanielDarrenJones** [comment]
@aryehraber that would be great, i'll let you know if we bump into any issues, thanks!

**Comment by aryehraber** [comment]
Cool, I just released `v1.5.0` 🎉 

Please re-open this issue (or a new one) if you notice any issues.
