### ISSUE TITLE
Error "Width or height needs to be defined." when using square images.

### ISSUE THREAD

**Issue by Burans** [aryehraber/statamic-color-extractor#2]
Hi!

Firstly - thank you very much for creating this plugin. I have been looking for / waiting for someone to make this since early v2.

Today, after importing some content and assets from an old site i'm remaking in Statamic i started to get this error whenever trying to use color extractor - 

`Width or height needs to be defined.`

After multiple hours of pulling my hair I've come to a suspicion that color extractor fails to process **square** images - images that have exactly the same width and height.

Seems weird but thats what i'm experiencing. I upload a 500x600 image and everything works as expected. Upload a 500x500 and I get the error.

Thanks again!

**Comment by aryehraber** [comment]
Hi @Burans, thanks for reporting this issue! I guess I never tested the addon with a perfectly square image 😂  Sorry to hear it cost you so many debugging hours... I've gone ahead and fixed it for you right away, release should be out in the next few minutes.
