### ISSUE TITLE
Performance issues.

### ISSUE THREAD

**Issue by Burans** [aryehraber/statamic-color-extractor#4]
Hi!

I've run into some performance issues and I'm not sure if it's my fault or not. :)

When in development and using handful of placeholder images all over the site Color Extractor worked fine. 
But now when I have started to fill the site with real content Color Extractor get gets really slow really fast.

A page with ~30 images takes ~10 seconds to load. When Color Extractor is removed the same page loads instantly. 

My guess is that Color Extractor does not cache the color data but calculates it on each page load?

Thank you!
Toms

**Comment by aryehraber** [comment]
Hmm, that doesn't sound quite right, after calculating each image's colour it should cache the value inside the Asset Container's `.yaml` file. I wrote a small section at the bottom of the docs: https://github.com/aryehraber/statamic-color-extractor#manually-editing-colors

Can you check whether the colours are getting saved there, and if not can you please provide more detailed info (your setup, versions, etc).

**Comment by aryehraber** [comment]
In case above wasn't totally clear, here's a screenshot from my dev project:

![Screenshot 2020-11-30 at 16 57 32](https://user-images.githubusercontent.com/5065331/100632556-3de69a80-332d-11eb-841c-f816b45a2fb7.jpg)

**Comment by Burans** [comment]
Yes, the colors are saved in the `.yaml` files correctly.

My setup:
1. Statamic 3.0.31
2. Color extractor 1.1.1

Not sure what more info I could provide to help pinpoint the problem.
The only thing I know for sure is that the more Color Extractor tags I use the slower the page gets and if I remove it completely the problem goes away. 

I will try to set up a new blank site and see if the problem persists.

**Comment by aryehraber** [comment]
Thanks for checking! 

So, the addon _should_ be checking the data in that `yaml` file instead of reprocessing the images... I'll take a look on my end when I next have a moment. Thanks for reporting!

**Comment by aryehraber** [comment]
@Burans I think I got to the bottom of this, pushing a fix in next release (available in a few minutes). 

Please let me know if it helped on your end or if you continue having performance issues after updating. Thanks!

**Comment by Burans** [comment]
Yes! Whatever you did seems to have solved the issue.
