### ISSUE TITLE
'Image must be a gd resource' 

### ISSUE THREAD

**Issue by andrew-ireland** [aryehraber/statamic-color-extractor#6]
I have followed the directions to use the addon, but I'm seeing the error 'Image must be a gd resource'. 

Not sure what's going on, but happy to provide additional details as needed.

**Comment by aryehraber** [comment]
Hi @andrew-ireland, did some digging and it looks like the underlying package has an issue with PHP 8 atm: 
https://github.com/thephpleague/color-extractor/issues/64

Unfortunately the package isn't well maintained these days so not sure if this will be fixed anytime soon. Either way, I'll be keeping an eye on it and update this addon if a fix is available.

**Comment by andrew-ireland** [comment]
Ahhh, of course... Thanks for the heads up/clarification — really appreciate it 👍
