### ISSUE TITLE
Antlers syntax in docs

### ISSUE THREAD

**Issue by helloDanuk** [aryehraber/statamic-color-extractor#7]
Wonderful plugin, thank you. However I am not sure if the antlers syntax is correct?
I need to write `{{ image:color_average }}` to get things work right.

With `{{ image | color }}` or `{{ image | color:average }}` I receive an error message.

**Comment by aryehraber** [comment]
Hi @helloDanuk, glad to hear you're enjoying it!

Would you be able to share some more details please:

- Statamic version
- Addon version 
- Error message (+ screenshot?)
- Relevant page data
- Relevant template code

Thanks!

**Comment by helloDanuk** [comment]
Sorry, I was a bit short. Here are all the details:

### Statamic and addon version

Statamic 3.1.22 Pro installed from statamic/statamic
Laravel 8.46.0
PHP 7.4.20
aryehraber/statamic-color-extractor 1.1.2
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.4.6
statamic/seo-pro 2.2.1

### Relevant page data

- I changed to `'fallback' => '#3c3c3c',` and `'default_type' => 'average',` in `config/color_extractor.php

#### public/assets/.meta/file.jpg.yaml

```
data:
  color_average: '#686DAC'
size: 4124737
last_modified: 1623486888
width: 5184
height: 3456
mime_type: image/jpeg
```

### Relevant template code

For simplicity I deleted most of the styling HTML 

```
{{ collection:lehrwerkstatt }}
    <div style="background-color: {{ teaser_bild:color_average }};">
        Works!
    </div>
{{ /collection:lehrwerkstatt }}

or

{{ collection:lehrwerkstatt }}
    {{ teaser_bild }}
    <div style="background-color: {{ url | color:average }};">
        Works too!
    </div>
    {{ /teaser_bild }}
{{ /collection:lehrwerkstatt }}

but

{{ collection:lehrwerkstatt }}
    <div style="background-color: {{ teaser_bild | color:average }};">
        Won't work. see error message
    </div>
{{ /collection:lehrwerkstatt }}
```

### Error message

<img width="1213" alt="Bildschirmfoto 2021-06-13 um 11 45 31" src="https://user-images.githubusercontent.com/8265902/121802500-e65eab00-cc3c-11eb-8d8f-33d51fd1fac4.png">


### Conclusion

Did I just used Antlers syntax the wrong way and was therefor confused that an other writing style exists?

**Comment by aryehraber** [comment]
Thanks for following up with the extra details! 

Nothing obvious is jumping out at me from your usage so I'll try and find some time in the coming week(s) to recreate on my end and investigate. I'm glad that you've found a workaround in the meantime to keep you going 👍

**Comment by aryehraber** [comment]
Hi @helloDanuk, apologies for the _very_ delayed response...

I finally got a chance to try and recreate the issue based on your example (iterating over a Collection), and the following works as expected for me (using latest Statamic + Addon):

```html
{{ collection:blog }}
  <div style="max-width: 300px;">
    <div style="padding: 20px; background: {{ banner_image | color:average }};">
      <img src="{{ glide:banner_image square="300" }}">
    </div>
  </div>
{{ /collection:blog }}
```

You've probably moved well beyond this now, but perhaps it was due to a missing image (`teaser_bild`) in one of your entries?  When I delete a `banner_image` in one of my entries, I get the same error as from your screenshot: `"Argument #1 ($asset) must be of type string, null given..."`.

Anyway, closing for now since it does seem to work as stated in the docs, feel free to re-open if this continue being an issue.
